# Generated by Django 5.2.5 on 2025-08-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_app', '0002_alter_sale_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('value', models.FloatField(default=0)),
                ('chart_type', models.CharField(choices=[('total_sales', 'Total Sales'), ('total_stock', 'Total Stock'), ('total_customers', 'Total Customers')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
