# Generated by Django 5.2.5 on 2025-08-28 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_app', '0006_invoice_invoiceitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='invoice',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='InvoiceItem',
        ),
    ]
