name: Django CI/CD

on:
  push:
    branches:
      - main        # Runs on any push to main
  pull_request:
    branches:
      - main        # Runs on PRs to main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ERP/requirements.txt

      # Run migrations
      - name: Run Migrations
        run: |
          python ERP/manage.py makemigrations --noinput
          python ERP/manage.py migrate --noinput

      # Collect static files
      - name: Collect Static Files
        run: python ERP/manage.py collectstatic --noinput

      # Run tests
      - name: Run Tests
        run: python ERP/manage.py test
