name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Create and activate virtual environment
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run migrations
      - name: Run Migrations
        run: |
          python manage.py makemigrations --noinput
          python manage.py migrate --noinput

      # Run tests (if you have any tests in tests.py)
      - name: Run Tests
        run: |
          python manage.py test
