name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up Python 3.13
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run migrations
      - name: Run Migrations
        run: |
          python manage.py makemigrations --noinput
          python manage.py migrate --noinput

      # Collect static files
      - name: Collect Static Files
        run: |
          python manage.py collectstatic --noinput

      # Run tests
      - name: Run Tests
        run: |
          python manage.py test
